plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ds.articleeditor'
    compileSdk 34

    defaultConfig {
        applicationId "com.ds.articleeditor"
        minSdk 24
        targetSdk 34
        versionCode 26
        versionName "1.32"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
